# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_cipher', [dirname(__file__)])
        except ImportError:
            import _cipher
            return _cipher
        if fp is not None:
            try:
                _mod = imp.load_module('_cipher', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _cipher = swig_import_helper()
    del swig_import_helper
else:
    import _cipher
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def new_intp():
  return _cipher.new_intp()
new_intp = _cipher.new_intp

def copy_intp(*args):
  return _cipher.copy_intp(*args)
copy_intp = _cipher.copy_intp

def delete_intp(*args):
  return _cipher.delete_intp(*args)
delete_intp = _cipher.delete_intp

def intp_assign(*args):
  return _cipher.intp_assign(*args)
intp_assign = _cipher.intp_assign

def intp_value(*args):
  return _cipher.intp_value(*args)
intp_value = _cipher.intp_value
class Cipher(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Cipher, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Cipher, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _cipher.new_Cipher()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _cipher.delete_Cipher
    __del__ = lambda self : None;
    def CleanUp(self): return _cipher.Cipher_CleanUp(self)
    def Prepare(self, *args): return _cipher.Cipher_Prepare(self, *args)
    def Activate(self, *args): return _cipher.Cipher_Activate(self, *args)
    def Encrypt(self, *args): return _cipher.Cipher_Encrypt(self, *args)
    def Decrypt(self, *args): return _cipher.Cipher_Decrypt(self, *args)
    def activated(self): return _cipher.Cipher_activated(self)
    def set_activated(self, *args): return _cipher.Cipher_set_activated(self, *args)
Cipher_swigregister = _cipher.Cipher_swigregister
Cipher_swigregister(Cipher)


def get_sequence(*args):
  return _cipher.get_sequence(*args)
get_sequence = _cipher.get_sequence
# This file is compatible with both classic and new-style classes.


